import Foundations
import Mathlib.Analysis.Convex.Extreme

/-! Extreme points cannot be generated by convex combinations of other points. -/

namespace Erdos957

/-- An indexed extreme point lies outside the convex hull of any subfamily
that omits its index, provided the indexed points are distinct. -/
theorem extreme_not_mem_convexHull_image {ι : Type*}
    (p : ι → Point) (hp : Function.Injective p) (i : ι)
    (hext : p i ∈ (convexHull ℝ (Set.range p)).extremePoints ℝ)
    (S : Set ι) (hi : i ∉ S) :
    p i ∉ convexHull ℝ (p '' S) := by
  have hnot := ((convex_convexHull ℝ (Set.range p)).mem_extremePoints_iff_mem_sdiff_convexHull_sdiff.mp hext).2
  intro hmem
  apply hnot
  apply convexHull_mono (s := p '' S)
    (t := convexHull ℝ (Set.range p) \ {p i}) ?_ hmem
  rintro z ⟨j, hj, rfl⟩
  refine ⟨subset_convexHull ℝ (Set.range p) ⟨j, rfl⟩, ?_⟩
  intro heq
  exact hi ((hp (Set.mem_singleton_iff.mp heq)) ▸ hj)

/-- An extreme point of a convex hull remains extreme in the hull of a
subfamily containing it. -/
theorem extreme_in_subfamily {ι κ : Type*}
    (p : ι → Point) (f : κ → ι) (j : κ)
    (hext : p (f j) ∈ (convexHull ℝ (Set.range p)).extremePoints ℝ) :
    (p ∘ f) j ∈ (convexHull ℝ (Set.range (p ∘ f))).extremePoints ℝ := by
  have hsub : convexHull ℝ (Set.range (p ∘ f)) ⊆
      convexHull ℝ (Set.range p) := by
    apply convexHull_mono
    rintro z ⟨k, rfl⟩
    exact ⟨f k, rfl⟩
  exact inter_extremePoints_subset_extremePoints_of_subset hsub
    ⟨subset_convexHull ℝ (Set.range (p ∘ f)) ⟨j, rfl⟩, hext⟩

end Erdos957
